# Changes here will be overwritten by Copier
_commit: e730ed7
_src_path: gh:audivir/copier-template
description: Package specs for pmg.
github_org: audivir
project_name: pmg-specs
project_slug: pmg_specs
project_type: shell
publishable: false
