#:schema https://raw.githubusercontent.com/audivir/pmg/main/schema.json
bin = { gawk = "bin/gawk" }
man = ["share/man/man1/gawk.1"]

test = '''test "$({{ cmd }} 'BEGIN { print 1 + 1 }')" = 2'''
[external]
brew = "gawk"
apt = "gawk"
apk = "gawk"
dnf = "gawk"
yum = "gawk"

[release]
type = "github"
repo = "audivir/gawk-static"

[download]
type = "github"

[assets]
glibc_x64 = "gawk-static-linux-amd64.tar.gz"
glibc_arm64 = "gawk-static-linux-arm64.tar.gz"
musl_x64 = "gawk-static-linux-musl-amd64.tar.gz"
musl_arm64 = "gawk-static-linux-musl-arm64.tar.gz"
macos_arm64 = "gawk-static-macos-arm64.tar.gz"
