#:schema https://raw.githubusercontent.com/audivir/pmg/main/schema.json
# the static zsh of zsh-bin; its installer points the paths within zsh to where it lives, and
# compiles its functions
content = true
links = { zsh = "{{ dir }}/bin/zsh" }
man = ["man/man1/zsh.1", "man/man1/zshall.1"]
post_install = '''
cd "$PREFIX/dir"
./share/zsh/5.8/scripts/relocate -d "{{ dir }}"
./bin/zsh -fc '
  setopt extended_glob                                 || exit
  zmodload -F zsh/files b:{zf_mv,zf_rm,zf_ln,zf_mkdir} || exit

  for pat in "[^[:upper:]]" "[[:upper:]]"; do
    for hex in ./share/terminfo/[[:xdigit:]][[:xdigit:]].zsh-bin(:t:r); do
      printf -v char "\\x$hex"
      [[ $char == $~pat ]] || continue
      [[ -e ./share/terminfo/$hex ]] || zf_mkdir -- ./share/terminfo/$hex || exit
      cp -- ./share/terminfo/$hex.zsh-bin/* ./share/terminfo/$hex/ || exit
      if [[ $char != [[:upper:]] ||
            ! ./share/terminfo/$char -ef ./share/terminfo/${(L)char} ]]; then
        [[ -e ./share/terminfo/$char ]] ||
          zf_ln -s -- $hex ./share/terminfo/$char 2>/dev/null ||
          zf_mkdir -- ./share/terminfo/$char || exit
        cp -- ./share/terminfo/$hex.zsh-bin/* ./share/terminfo/$char/ || exit
      fi
      zf_rm -rf -- ./share/terminfo/$hex.zsh-bin || exit
    done
  done

  for file in ./share/zsh/5.8/functions/*~*.[^/]#(.); do
    tmp=$file.tmp.$$.zwc
    zf_rm -f -- $tmp $file.zwc || exit
    zcompile -R -- $tmp $file  || exit
    zf_mv -f -- $tmp $file.zwc || exit
  done'
'''

test = '{{ cmd }} -fc "zmodload zsh/datetime"'
[external]
brew = "zsh"
apt = "zsh"
apk = "zsh"
dnf = "zsh"
yum = "zsh"

[release]
type = "github"
repo = "romkatv/zsh-bin"

[download]
type = "github"

[assets]
glibc_x64 = "zsh-5.8-linux-x86_64.tar.gz"
glibc_arm64 = "zsh-5.8-linux-aarch64.tar.gz"
musl_x64 = "zsh-5.8-linux-x86_64.tar.gz"
musl_arm64 = "zsh-5.8-linux-aarch64.tar.gz"
macos_arm64 = "zsh-5.8-darwin-arm64.tar.gz"
