#:schema https://raw.githubusercontent.com/audivir/pmg/main/schema.json
# zsh finds its functions relative to its binary, so the whole archive is the package dir; they
# are compiled, which makes them load faster
content = true
links = { zsh = "{{ dir }}/bin/zsh" }
man = ["share/man/man1/*.1"]
post_install = '''
cd "$PREFIX/dir"
./bin/zsh -fc '
  setopt extended_glob                 || exit
  zmodload -F zsh/files b:{zf_mv,zf_rm} || exit
  for file in ./share/zsh/*/functions/*~*.[^/]#(.); do
    tmp=$file.tmp.$$.zwc
    zf_rm -f -- $tmp $file.zwc || exit
    zcompile -R -- $tmp $file  || exit
    zf_mv -f -- $tmp $file.zwc || exit
  done'
'''

test = '{{ cmd }} -fc "zmodload zsh/datetime"'
[external]
brew = "zsh"
apt = "zsh"
apk = "zsh"
dnf = "zsh"
yum = "zsh"

[release]
type = "github"
repo = "audivir/zsh-static"

[download]
type = "github"

[assets]
glibc_x64 = "zsh-static-linux-amd64.tar.gz"
glibc_arm64 = "zsh-static-linux-arm64.tar.gz"
musl_x64 = "zsh-static-linux-musl-amd64.tar.gz"
musl_arm64 = "zsh-static-linux-musl-arm64.tar.gz"
macos_arm64 = "zsh-static-macos-arm64.tar.gz"
